# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cb1e41f84c49db869450e52be71d04ee39a7ac6f3569dfc0141e3c1817168df155936c69fb8ed696b3e8cd17d39a4d6ec079f2070a2b3e894aed5a016b02d16
  app_id: 302
  app_name: zeta_bytes
  app_secret: 376f88a8e8788b77302dbf95903bafed
  app_email: surendar.marudhachalam@quikr.com
  api_base: "https://api.quikr.com"

test:
  secret_key_base: 07321ed14c5093fb7d2b9d71fb8cf99cee2ff29d4b282f106b718daa56f5dd83c0050adde0ec41caefc9ac1a3d11765d73d8ce58515ec9f8039fc15aedfab807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  app_id: 302
  app_name: zeta_bytes
  app_secret: 376f88a8e8788b77302dbf95903bafed
  app_email: surendar.marudhachalam@quikr.com
  api_base: "https://api.quikr.com"
